/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSurveysRouteImport } from './routes/admin.surveys'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as DirectorySlugRouteImport } from './routes/directory.$slug'
import { Route as SurveysSlugRouteImport } from './routes/surveys.$slug'
import { Route as AdminAreasIdRouteImport } from './routes/admin.areas.$id'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin.surveys.index'
import { Route as AdminSurveysIdRouteImport } from './routes/admin.surveys.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysRoute = AdminSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectoryRoute,
} as any)
const DirectorySlugRoute = DirectorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DirectoryRoute,
} as any)
const SurveysSlugRoute = SurveysSlugRouteImport.update({
  id: '/surveys/$slug',
  path: '/surveys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAreasIdRoute = AdminAreasIdRouteImport.update({
  id: '/areas/$id',
  path: '/areas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSurveysRoute,
} as any)
const AdminSurveysIdRoute = AdminSurveysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSurveysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/directory': typeof DirectoryRouteWithChildren
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/admin/areas/$id': typeof AdminAreasIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/admin': typeof AdminIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/admin/areas/$id': typeof AdminAreasIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/directory': typeof DirectoryRouteWithChildren
  '/admin/surveys': typeof AdminSurveysRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/surveys/$slug': typeof SurveysSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/admin/areas/$id': typeof AdminAreasIdRoute
  '/admin/surveys/$id': typeof AdminSurveysIdRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/directory'
    | '/admin/surveys'
    | '/admin/login'
    | '/directory/$slug'
    | '/surveys/$slug'
    | '/admin/'
    | '/directory/'
    | '/admin/areas/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/directory/$slug'
    | '/surveys/$slug'
    | '/admin'
    | '/directory'
    | '/admin/areas/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/directory'
    | '/admin/surveys'
    | '/admin_/login'
    | '/directory/$slug'
    | '/surveys/$slug'
    | '/admin/'
    | '/directory/'
    | '/admin/areas/$id'
    | '/admin/surveys/$id'
    | '/admin/surveys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DirectoryRoute: typeof DirectoryRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  SurveysSlugRoute: typeof SurveysSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys': {
      id: '/admin/surveys'
      path: '/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AdminSurveysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/directory/$slug': {
      id: '/directory/$slug'
      path: '/$slug'
      fullPath: '/directory/$slug'
      preLoaderRoute: typeof DirectorySlugRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/surveys/$slug': {
      id: '/surveys/$slug'
      path: '/surveys/$slug'
      fullPath: '/surveys/$slug'
      preLoaderRoute: typeof SurveysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/areas/$id': {
      id: '/admin/areas/$id'
      path: '/areas/$id'
      fullPath: '/admin/areas/$id'
      preLoaderRoute: typeof AdminAreasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminSurveysRoute
    }
    '/admin/surveys/$id': {
      id: '/admin/surveys/$id'
      path: '/$id'
      fullPath: '/admin/surveys/$id'
      preLoaderRoute: typeof AdminSurveysIdRouteImport
      parentRoute: typeof AdminSurveysRoute
    }
  }
}

interface AdminSurveysRouteChildren {
  AdminSurveysIdRoute: typeof AdminSurveysIdRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

const AdminSurveysRouteChildren: AdminSurveysRouteChildren = {
  AdminSurveysIdRoute: AdminSurveysIdRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}

const AdminSurveysRouteWithChildren = AdminSurveysRoute._addFileChildren(
  AdminSurveysRouteChildren,
)

interface AdminRouteChildren {
  AdminSurveysRoute: typeof AdminSurveysRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAreasIdRoute: typeof AdminAreasIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSurveysRoute: AdminSurveysRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAreasIdRoute: AdminAreasIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DirectoryRouteChildren {
  DirectorySlugRoute: typeof DirectorySlugRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectorySlugRoute: DirectorySlugRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DirectoryRoute: DirectoryRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  SurveysSlugRoute: SurveysSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
